---
# tasks file for flyway
- name: Creating directory for flyway
  file: path={{flyway_root}} state=directory

- name: Downloading flyway
  get_url: url={{flyway_real_url}} dest={{flyway_root}}

- name: Unpacking flyway
  unarchive: copy=no src={{flyway_root}}/flyway-commandline-{{flyway_version}}.tar.gz dest={{flyway_root}}

- name: removing downloaded copy
  file: path={{flyway_root}}/flyway-commandline-{{flyway_version}}.tar.gz state=absent

- name: creating synmink in /usr/bin
  file: src={{flyway_binary}} dest=/usr/bin/flyway state=link

- name: fixing permissions to binary
  file: path={{flyway_binary}} mode=766 state=file
